name: ekrhizoc
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7                 # PSF
  - pip=20.0                    # MIT
  - poetry=1.0.0                # MIT
  - pre-commit=2.2              # MIT
  - shellcheck=0.7.0            # GPL-3.0
  - conda-pack=0.4.0            # BSD
